data:
  labels: data/labels/5_fold/iemocap_5fold_1.csv
  pitch_feature_dir: data/processed/features/iemocap/pitch_features
  w2v2_feature_dir: data/processed/features/iemocap/wav2vec2-large-robust_l12

train:
  epochs: 500
  batch_size: 1
  learning_rate: 1e-5
  num_workers: 2
  pin_memory: True
  seed: 42
  loss: mse           


model:
  hidden_dim: 1024
  num_heads: 8