data:
  audio_path: data/IEMOCAP
  audio_model_path: pretrained_model/wav2vec2-base-960h
  audio_tokenizer_path: pretrained_model/wav2vec2-base-960h

train:
  epochs: 30
  batch_size: 4
  learning_rate: 2e-5
  hidden_size: 1024
  
